version: '3.7'

services:
  web:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./src/:/usr/projects/celery_plus_websocket/src
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.3
    volumes:
        - ./postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env.prod.db
    ports:
        - "5431:5432"
  redis:
    image: redis
    restart: always
    command: ["redis-server", "--port", "6379", "--appendonly", "yes","--maxmemory", "2gb", "--maxmemory-policy", "allkeys-lru"]
  celery_worker:
    build: ./src
    command: >
            bash -c "celery -A config worker -l INFO -n worker1@worker
            && celery -A config worker -l INFO -n worker3@worker -Q queue1"
    volumes:
      - ./src/:/usr/projects/celery_plus_websocket/src
    restart: always
    depends_on:
      - web
      - redis
  celery_beat:
    build: ./src
    command: "celery -A config beat -l INFO"
    volumes:
      - ./src/:/usr/projects/celery_plus_websocket/src
    restart: always
    depends_on:
      - web
      - redis
