# Generated by Django 3.2.9 on 2021-11-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_balance', models.PositiveIntegerField()),
                ('apples', models.PositiveIntegerField()),
                ('bananas', models.PositiveIntegerField()),
                ('pineapples', models.PositiveIntegerField()),
                ('peaches', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('execution_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'SUCCESS'), ('2', 'ERROR'), ('3', 'INFO')], max_length=1)),
            ],
        ),
    ]
